#!/data/data/com.termux/files/usr/bin/bash

# ============================================================
#   Termux Desktop Launcher
#   Usage:
#     startdesktop              -> Termux:X11 (recommended)
#     startdesktop rdp          -> xRDP mode
#     startdesktop novnc        -> noVNC browser mode
#     startdesktop menu         -> show selection menu
#     startdesktop stop         -> kill all desktop sessions
#     startdesktop --nogpu      -> disable GPU acceleration
#     startdesktop --legacy     -> use legacy X11 drawing
#     startdesktop --nodbus     -> start without dbus-launch
#     startdesktop --debug      -> show startup logs
#     startdesktop --help       -> show help
#   Repo : github.com/Tanmay-1122/Termux-desktop
# ============================================================

set -eo pipefail

export PREFIX="${PREFIX:-/data/data/com.termux/files/usr}"
export HOME="${HOME:-/data/data/com.termux/files/home}"
export TMPDIR="${TMPDIR:-$PREFIX/tmp}"
export PATH="$PREFIX/bin:/system/bin:/system/xbin:$PATH"

# ── Colors ───────────────────────────────────────────────────
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
CYAN='\033[0;36m'
BOLD='\033[1m'
DIM='\033[2m'
NC='\033[0m'

# ── Config file ──────────────────────────────────────────────
CONFIG_DIR="$PREFIX/etc/termux-desktop"
CONFIG_FILE="$CONFIG_DIR/configuration.conf"

load_config() {
    if [ -f "$CONFIG_FILE" ]; then
        source "$CONFIG_FILE" 2>/dev/null || true
    fi
}

save_config() {
    mkdir -p "$CONFIG_DIR" 2>/dev/null
    cat > "$CONFIG_FILE" << CONF
# Termux Desktop Configuration
PROJECT_VER=$(cat "$HOME/.termux-desktop-version" 2>/dev/null || echo "1.4")
# Generated by start-desktop
DESKTOP_MODE=${MODE:-x11}
DISPLAY_NUM=${DISPLAY_NUM:-0}
NOGPU=${NOGPU:-false}
LEGACY=${LEGACY:-false}
NODBUS=${NODBUS:-false}
CONF
}

# ── GPU Detection ────────────────────────────────────────────
detect_gpu() {
    local gpu="unknown"
    local chipset=$(getprop ro.hardware 2>/dev/null || true)
    local board=$(getprop ro.board.platform 2>/dev/null || true)
    if echo "$chipset $board" | grep -qi "qcom\|msm\|snapdragon"; then gpu="adreno"
    elif echo "$chipset $board" | grep -qi "mali\|arm\|exynos"; then gpu="mali"
    elif echo "$chipset $board" | grep -qi "xclipse"; then gpu="xclipse"
    fi
    echo "$gpu"
}

# ── GPU Environment ──────────────────────────────────────────
setup_gpu_env() {
    if [ "$NOGPU" = "true" ]; then
        echo "[*] GPU acceleration disabled (--nogpu)"
        return
    fi
    local gpu=$(detect_gpu)
    if command -v virgl_test_server_android &>/dev/null; then
        echo "[*] Initializing VirGL GPU acceleration (GPU: $gpu)..."
        virgl_test_server_android &>/dev/null &
        sleep 1
        if pgrep -f virgl_test_server &>/dev/null; then
            export GALLIUM_DRIVER=virpipe
            export MESA_GL_VERSION_OVERRIDE=4.3COMPAT
            export MESA_GLES_VERSION_OVERRIDE=3.2
            export MESA_NO_ERROR=1
            echo "[OK] VirGL acceleration active (GPU: $gpu)"
        else
            echo "[!] VirGL failed to start. Using software rendering."
        fi
    elif [ "$gpu" = "adreno" ] && command -v vulkaninfo &>/dev/null; then
        export GALLIUM_DRIVER=zink
        export MESA_GL_VERSION_OVERRIDE=4.3COMPAT
        export ZINK_DESCRIPTORS=lazy
        echo "[OK] Zink/Vulkan acceleration active (GPU: $gpu)"
    else
        echo "[!] No GPU acceleration available (GPU: $gpu). Software rendering."
    fi
}

# ── IP Helpers ───────────────────────────────────────────────
get_ip() {
    local iface="$1"
    local addr=""
    if command -v ip &>/dev/null; then
        addr=$(ip addr show "$iface" 2>/dev/null \
               | grep -oE 'inet [0-9.]+' | awk '{print $2}' | head -1)
    fi
    if [ -z "$addr" ] && command -v ifconfig &>/dev/null; then
        addr=$(ifconfig "$iface" 2>/dev/null | grep 'inet ' | awk '{print $2}' | head -1)
    fi
    echo "$addr"
}

list_all_ips() {
    local ips=""
    if command -v ip &>/dev/null; then
        ips=$(ip -4 addr show | grep -oE 'inet [0-9.]+' | awk '{print $2}' | grep -v '^127\.')
    elif command -v ifconfig &>/dev/null; then
        ips=$(ifconfig | grep -oE 'inet [0-9.]+' | awk '{print $2}' | grep -v '^127\.')
    fi
    echo "$ips"
}

detect_best_ip() {
    local route_ip=""
    if command -v ip &>/dev/null; then
        route_ip=$(ip route get 8.8.8.8 2>/dev/null | grep -oP 'src \K[\d.]+' | head -1)
    fi
    if [ -n "$route_ip" ]; then echo "$route_ip"; return; fi

    if command -v hostname &>/dev/null; then
        local host_ip=$(hostname -I 2>/dev/null | awk '{print $1}')
        if [ -n "$host_ip" ]; then echo "$host_ip"; return; fi
    fi

    local first=$(list_all_ips | head -1)
    if [ -n "$first" ]; then echo "$first"; return; fi

    echo ""
}

WIFI_IP=""
USB_IP=""
USB_IFACE=""

for iface in wlan0 wlan1 ccmni0; do
    IP=$(get_ip "$iface")
    if [ -n "$IP" ]; then WIFI_IP="$IP"; break; fi
done

for iface in rndis0 usb0 eth0 rmnet_usb0; do
    IP=$(get_ip "$iface")
    if [ -n "$IP" ]; then USB_IP="$IP"; USB_IFACE="$iface"; break; fi
done

BEST_IP="${WIFI_IP:-$USB_IP}"
if [ -z "$BEST_IP" ]; then
    BEST_IP=$(detect_best_ip)
fi

# ── Argument Parsing ─────────────────────────────────────────
MODE="x11"
DISPLAY_NUM=0
NOGPU=false
LEGACY=false
NODBUS=false
DEBUG=false

show_help() {
    cat << 'HELP'
Usage: startdesktop [MODE] [OPTIONS]

Modes:
  (none)       Start Termux:X11 (default, recommended)
  rdp          Start xRDP (connect via Windows Remote Desktop)
  novnc        Start noVNC (browser-based access)
  menu         Show interactive mode selection
  stop         Kill all desktop sessions

Options:
  --nogpu      Disable GPU hardware acceleration
  --legacy     Use legacy X11 drawing (-legacy-drawing)
  --nodbus     Start without dbus-launch wrapper
  --debug      Show startup logs and commands
  --help,-h    Show this help message

Network:
  RDP address  <IP>:3389  (shown in menu/mode banners)
  noVNC URL    http://<IP>:6080/vnc.html

Examples:
  startdesktop                  # GPU-accelerated X11 session
  startdesktop --nogpu          # Software rendering
  startdesktop rdp              # xRDP mode (auto-detects IP)
  startdesktop novnc            # Browser mode (auto-detects IP)
  startdesktop menu             # Interactive menu
  startdesktop stop             # Kill everything

HELP
    exit 0
}

while [ $# -gt 0 ]; do
    case "$1" in
        x11|X11|"")       MODE="x11" ;;
        rdp|RDP)           MODE="rdp" ;;
        novnc|noVNC)       MODE="novnc" ;;
        menu)              MODE="menu" ;;
        stop|kill)         MODE="stop" ;;
        --nogpu)           NOGPU=true ;;
        --legacy)          LEGACY=true ;;
        --nodbus)          NODBUS=true ;;
        --debug)           DEBUG=true ;;
        --help|-h)         show_help ;;
        *)                 echo "[!] Unknown option '$1'. Use --help."; exit 1 ;;
    esac
    shift
done

debug_log() {
    if [ "$DEBUG" = "true" ]; then
        echo -e "${DIM}[DEBUG] $1${NC}"
    fi
}

# ── Stop Mode ────────────────────────────────────────────────
if [ "$MODE" = "stop" ]; then
    echo "[*] Stopping all desktop sessions..."
    pkill xrdp 2>/dev/null || true
    pkill xrdp-sesman 2>/dev/null || true
    pkill Xtigervnc 2>/dev/null || true
    pkill Xvnc 2>/dev/null || true
    pkill xfce4-session 2>/dev/null || true
    pkill websockify 2>/dev/null || true
    pkill -f "termux.x11" 2>/dev/null || true
    vncserver -kill :1 2>/dev/null || true
    pkill -f virgl_test_server 2>/dev/null || true
    rm -rf "$PREFIX/tmp/.X"* 2>/dev/null || true
    rm -rf "$PREFIX/tmp/.X11-unix/"* 2>/dev/null || true
    echo "[OK] Desktop stopped."
    exit 0
fi

# ── Menu Mode ────────────────────────────────────────────────
if [ "$MODE" = "menu" ]; then
    clear
    echo ""
    echo "╔══════════════════════════════════════════════════╗"
    echo "║        Termux Desktop Launcher v${PROJECT_VER}         ║"
    echo "╠══════════════════════════════════════════════════╣"
    echo "║  Network Status:                                ║"
    if [ -n "$USB_IP" ]; then
        printf "║   USB  (%-6s) : %-28s║\n" "$USB_IFACE" "$USB_IP"
    else
        echo "║   USB            : Not detected                  ║"
    fi
    printf "║   WiFi (wlan0)   : %-28s║\n" "${WIFI_IP:-Not detected}"
    echo "╠══════════════════════════════════════════════════╣"
    echo "║  Select Display Mode:                           ║"
    echo "║                                                  ║"
    echo "║   A) Termux:X11  — Recommended (fastest)       ║"
    echo "║   B) xRDP        — Windows Remote Desktop      ║"
    echo "║   C) noVNC       — Any browser                 ║"
    echo "║                                                  ║"
    echo "╠══════════════════════════════════════════════════╣"
    echo "║  Quick Tools:                                   ║"
    echo "║   D) Dashboard   — System health               ║"
    echo "║   T) Theme       — Change desktop theme        ║"
    echo "║   M) Manage Apps — Install/remove apps         ║"
    echo "║   S) Stop        — Kill current desktop        ║"
    echo "╚══════════════════════════════════════════════════╝"
    echo ""
    if [ -n "$BEST_IP" ]; then
        echo "   RDP address: $BEST_IP:3389"
        echo "   noVNC URL  : http://$BEST_IP:6080/vnc.html"
    else
        echo "   WiFi not detected — RDP/noVNC may not work"
    fi
    echo ""
    read -rp "   Choice [A/B/C/D/T/M/S]: " CHOICE
    CHOICE=$(echo "$CHOICE" | tr '[:lower:]' '[:upper:]')
    case "$CHOICE" in
        D) exec bash "$HOME/dashboard.sh" ;;
        T) exec bash "$HOME/theme.sh" ;;
        M) exec bash "$HOME/manage-apps.sh" ;;
        A|"") MODE="x11" ;;
        B)    MODE="rdp" ;;
        C)    MODE="novnc" ;;
        S)    exec bash "$0" stop ;;
        *)    MODE="x11" ;;
    esac
fi

# ── Cleanup previous session ─────────────────────────────────
echo "[*] Cleaning previous session..."
pkill xrdp 2>/dev/null || true
pkill xrdp-sesman 2>/dev/null || true
pkill Xtigervnc 2>/dev/null || true
pkill Xvnc 2>/dev/null || true
pkill xfce4-session 2>/dev/null || true
pkill websockify 2>/dev/null || true
pkill -f "termux.x11" 2>/dev/null || true
vncserver -kill :1 2>/dev/null || true
pkill -f virgil_test_server 2>/dev/null || true
rm -rf "$PREFIX/tmp/.X"* 2>/dev/null || true
rm -rf "$PREFIX/tmp/.X11-unix/"* 2>/dev/null || true
sleep 1

# ── Setup GPU ────────────────────────────────────────────────
setup_gpu_env

# ════════════════════════════════════════════════════════════
# Shared Helpers
# ════════════════════════════════════════════════════════════
setup_xsession() {
    export XDG_RUNTIME_DIR="$PREFIX/tmp/runtime-$UID"
    mkdir -p "$XDG_RUNTIME_DIR"
    chmod 700 "$XDG_RUNTIME_DIR"
    cat > ~/.xsession << 'EOL'
export XDG_RUNTIME_DIR=/data/data/com.termux/files/usr/tmp/runtime-0
mkdir -p $XDG_RUNTIME_DIR
chmod 700 $XDG_RUNTIME_DIR
dbus-launch --exit-with-session xfce4-session
EOL
    chmod +x ~/.xsession
    echo "startxfce4" > ~/.Xclients
    chmod +x ~/.Xclients
}

configure_xrdp() {
    local XRDP_INI="$PREFIX/etc/xrdp/xrdp.ini"
    [ ! -f "$XRDP_INI" ] && return 1
    sed -i 's/^autorun=.*/autorun=Direct-VNC/' "$XRDP_INI"
    grep -q '^autorun=' "$XRDP_INI" || \
        sed -i '/^\[Globals\]/a autorun=Direct-VNC' "$XRDP_INI"
    sed -i 's/^crypt_level=high/crypt_level=none/' "$XRDP_INI"
    grep -q '\[Direct-VNC\]' "$XRDP_INI" || cat >> "$XRDP_INI" << 'XEOF'

[Direct-VNC]
name=NoLogin
lib=libvnc.so
username=na
password=na
ip=127.0.0.1
port=5901
XEOF
}

start_vnc() {
    echo "[*] Starting VNC on :1 (port 5901)..."
    vncserver :1 -geometry 1366x768 -depth 24 \
        -SecurityTypes None -localhost no 2>/dev/null
    sleep 2
    if ! pgrep -f "Xvnc.*:1" >/dev/null && ! pgrep -f "Xtigervnc.*:1" >/dev/null; then
        echo "[!!] VNC failed. Check: ~/.vnc/"
        exit 1
    fi
    echo "[OK] VNC running on :1"
}

_wait_for_session() {
    local pid="$1" label="$2" max_wait="${3:-10}"
    local waited=0
    while [ $waited -lt $max_wait ]; do
        if kill -0 "$pid" 2>/dev/null; then
            if pgrep -f "xfce4-session" >/dev/null 2>&1; then
                return 0
            fi
        else
            echo "[!] $label failed to start (process exited)"
            return 1
        fi
        sleep 1
        waited=$((waited + 1))
    done
    echo "[!] $label did not start within ${max_wait}s — check installation"
    return 1
}

_start_picom() {
    if command -v picom &>/dev/null; then
        local picom_conf="$HOME/.config/picom/picom.conf"
        if [ -f "$picom_conf" ]; then
            picom --config "$picom_conf" -b >/dev/null 2>&1 &
            echo "[OK] Picom compositor started (blur enabled)"
        else
            picom -b >/dev/null 2>&1 &
            echo "[OK] Picom compositor started (default config)"
        fi
    else
        echo "[!] Picom not installed — blur unavailable."
    fi
}

# ════════════════════════════════════════════════════════════
# MODE X11 — Termux:X11
# ════════════════════════════════════════════════════════════
start_x11() {
    echo ""
    echo "[*] Starting Termux:X11 mode..."
    termux-wake-lock 2>/dev/null || true

    pulseaudio --start \
        --load="module-native-protocol-tcp auth-ip-acl=127.0.0.1 auth-anonymous=1" \
        --exit-idle-time=-1 2>/dev/null || true

    export XDG_RUNTIME_DIR="${TMPDIR:-$PREFIX/tmp}"
    mkdir -p "$XDG_RUNTIME_DIR/.X11-unix"
    chmod 1777 "$XDG_RUNTIME_DIR/.X11-unix" 2>/dev/null || true

    local X11_ARGS=""
    [ "$LEGACY" = "true" ] && X11_ARGS="$X11_ARGS -legacy-drawing"
    debug_log "termux-x11 :0 $X11_ARGS"
    termux-x11 :0 $X11_ARGS >/dev/null 2>&1 &
    sleep 4

    echo "[*] Launching Termux:X11 app..."
    if command -v am &>/dev/null; then
        if am start --user 0 \
            -n com.termux.x11/com.termux.x11.MainActivity \
            >/dev/null 2>&1; then
            echo "[OK] Termux:X11 app launched"
        else
            echo "[!!] Could not launch automatically — open Termux:X11 manually"
        fi
    else
        echo "[!] Please open the Termux:X11 app on your phone."
    fi
    sleep 2

    export PULSE_SERVER=127.0.0.1
    export DISPLAY=:0
    export TMPDIR="$PREFIX/tmp"

    local STARTUP_CMD="xfce4-session"
    local DBUS_CMD=""
    if [ "$NODBUS" = "false" ]; then
        DBUS_CMD="dbus-launch --exit-with-session"
    else
        DBUS_CMD="exec"
    fi

    echo ""
    echo "╔══════════════════════════════════════════════════╗"
    echo "║       Termux:X11  MODE  ACTIVE                  ║"
    echo "╠══════════════════════════════════════════════════╣"
    echo "║   Termux:X11 app should show your desktop       ║"
    echo "║   XFCE4 is launching — please wait a moment     ║"
    echo "║   Press Ctrl+C to stop                          ║"
    echo "╚══════════════════════════════════════════════════╝"
    echo ""

    debug_log "Command: $DBUS_CMD $STARTUP_CMD"
    $DBUS_CMD $STARTUP_CMD >/dev/null 2>&1 &
    XFCE_PID=$!
    _wait_for_session "$XFCE_PID" "XFCE4 session" 10 || true
    _start_picom
    wait $XFCE_PID
}

# ════════════════════════════════════════════════════════════
# MODE RDP — xRDP
# ════════════════════════════════════════════════════════════
start_rdp() {
    echo ""
    echo "[*] Starting xRDP mode..."
    if ! command -v xrdp &>/dev/null; then
        echo "[!] xRDP not installed. Installing..."
        if ! pkg install -y xrdp 2>/dev/null; then
            echo "[!!] Failed to install xrdp. Try: pkg install xrdp"
            exit 1
        fi
        echo "[OK] xrdp installed"
    fi

    termux-wake-lock 2>/dev/null || true
    setup_xsession
    configure_xrdp
    start_vnc

    echo "[*] Launching XFCE4..."
    export DISPLAY=:1
    dbus-launch --exit-with-session xfce4-session \
        > "$PREFIX/tmp/xfce4.log" 2>&1 &
    XFCE_PID=$!
    _wait_for_session "$XFCE_PID" "XFCE4 session" 10 || true
    _start_picom

    echo "[*] Starting xRDP on port 3389..."
    xrdp-sesman > "$PREFIX/tmp/xrdp-sesman.log" 2>&1 &
    sleep 1
    xrdp > "$PREFIX/tmp/xrdp.log" 2>&1 &
    sleep 2

    if ! pgrep -x "xrdp" >/dev/null; then
        echo "[!!] xRDP failed. Log:"; cat "$PREFIX/tmp/xrdp.log"
        exit 1
    fi
    echo "[OK] xRDP running on port 3389"

    echo ""
    echo "╔══════════════════════════════════════════════════╗"
    echo "║           xRDP  MODE  ACTIVE                    ║"
    echo "╠══════════════════════════════════════════════════╣"
    echo "║   Connect using Windows Remote Desktop (mstsc)  ║"
    echo "║                                                  ║"
    [ -n "$WIFI_IP" ] && printf "║   WiFi  → %-37s║\n" "$WIFI_IP:3389"
    [ -n "$USB_IP"  ] && printf "║   USB   → %-37s║\n" "$USB_IP:3389"
    [ -z "$WIFI_IP" ] && [ -z "$USB_IP" ] && \
        echo "║   No IP detected — check connection             ║"
    echo "║                                                  ║"
    echo "║   Leave username/password blank                  ║"
    echo "║   Press Ctrl+C to stop                           ║"
    echo "╚══════════════════════════════════════════════════╝"
    echo ""
    wait $XFCE_PID
}

# ════════════════════════════════════════════════════════════
# MODE NOVNC — browser access
# ════════════════════════════════════════════════════════════
start_novnc() {
    echo ""
    echo "[*] Starting noVNC mode..."
    termux-wake-lock 2>/dev/null || true

    command -v websockify &>/dev/null || {
        echo "[*] Installing websockify..."
        pkg install -y websockify || { echo "[!!] websockify install failed"; exit 1; }
    }

    NOVNC_DIR="$HOME/noVNC"
    if [ ! -d "$NOVNC_DIR" ]; then
        echo "[*] Downloading noVNC web client..."
        local novnc_url="https://github.com/novnc/noVNC/archive/refs/heads/master.zip"
        local novnc_zip="$TMPDIR/novnc.zip"
        if command -v aria2c &>/dev/null; then
            aria2c -x 4 -s 4 --connect-timeout=10 --timeout=30 \
                --max-tries=3 --retry-wait=2 \
                --allow-overwrite=true --auto-file-renaming=false \
                "$novnc_url" -d "$TMPDIR" -o "novnc.zip" \
                -q 2>/dev/null || true
        fi
        if [ ! -f "$novnc_zip" ] || [ ! -s "$novnc_zip" ]; then
            wget -c -q "$novnc_url" -O "$novnc_zip" || true
        fi
        [ -f "$novnc_zip" ] && unzip -q "$novnc_zip" -d "$HOME" && \
        mv "$HOME/noVNC-master" "$NOVNC_DIR" && \
        rm -f "$novnc_zip" || true
    fi

    setup_xsession
    start_vnc

    echo "[*] Launching XFCE4..."
    export DISPLAY=:1
    dbus-launch --exit-with-session xfce4-session \
        > "$PREFIX/tmp/xfce4.log" 2>&1 &
    XFCE_PID=$!
    _wait_for_session "$XFCE_PID" "XFCE4 session" 10 || true
    _start_picom

    echo "[*] Starting websockify on port 6080..."
    if [ -d "$NOVNC_DIR" ]; then
        websockify --web="$NOVNC_DIR" 6080 localhost:5901 \
             > "$PREFIX/tmp/websockify.log" 2>&1 &
    else
        websockify 6080 localhost:5901 \
             > "$PREFIX/tmp/websockify.log" 2>&1 &
    fi
    sleep 2

    echo ""
    echo "╔══════════════════════════════════════════════════╗"
    echo "║           noVNC  MODE  ACTIVE                   ║"
    echo "╠══════════════════════════════════════════════════╣"
    echo "║   Open in any browser on your network:          ║"
    echo "║                                                  ║"
    [ -n "$WIFI_IP" ] && printf "║   http://%-40s║\n" "$WIFI_IP:6080/vnc.html"
    [ -n "$USB_IP"  ] && printf "║   http://%-40s║\n" "$USB_IP:6080/vnc.html"
    [ -z "$BEST_IP" ] && \
        echo "║   No IP detected — check WiFi                   ║"
    echo "║                                                  ║"
    echo "║   Works on Windows, Mac, Linux, iOS, Android    ║"
    echo "║   No app needed — just a browser                ║"
    echo "║   Press Ctrl+C to stop                           ║"
    echo "╚══════════════════════════════════════════════════╝"
    echo ""
    wait $XFCE_PID
}

# ════════════════════════════════════════════════════════════
# Launch
# ════════════════════════════════════════════════════════════
save_config
case "$MODE" in
    x11)   start_x11   ;;
    rdp)   start_rdp   ;;
    novnc) start_novnc ;;
esac
